{
  "perro": {"patas": 4, "pico": 0, "alas": 0},
  "gato": {"patas": 4, "pico": 0, "alas": 0},
  "vaca": {"patas": 4, "pico": 0, "alas": 0},
  "caballo": {"patas": 4, "pico": 0, "alas": 0},
  "conejo": {"patas": 4, "pico": 0, "alas": 0},
  "cerdo": {"patas": 4, "pico": 0, "alas": 0},
  "oveja": {"patas": 4, "pico": 0, "alas": 0},
  "león": {"patas": 4, "pico": 0, "alas": 0},
  "tigre": {"patas": 4, "pico": 0, "alas": 0},
  "elefante": {"patas": 4, "pico": 0, "alas": 0},
  "delfín": {"patas": 0, "pico": 0, "alas": 0},
  "ballena": {"patas": 0, "pico": 0, "alas": 0},
  "mono": {"patas": 4, "pico": 0, "alas": 0},
  "oso": {"patas": 4, "pico": 0, "alas": 0},
  "jirafa": {"patas": 4, "pico": 0, "alas": 0},
  "zorro": {"patas": 4, "pico": 0, "alas": 0},
  "lobo": {"patas": 4, "pico": 0, "alas": 0},
  "rinoceronte": {"patas": 4, "pico": 0, "alas": 0},
  "murciélago": {"patas": 2, "pico": 0, "alas": 2},
  "ornitorrinco": {"patas": 4, "pico": 0, "alas": 0},
  "gallina": {"patas": 2, "pico": 1, "alas": 2},
  "pato": {"patas": 2, "pico": 1, "alas": 2},
  "ganso": {"patas": 2, "pico": 1, "alas": 2},
  "loro": {"patas": 2, "pico": 1, "alas": 2},
  "águila": {"patas": 2, "pico": 1, "alas": 2},
  "paloma": {"patas": 2, "pico": 1, "alas": 2},
  "flamenco": {"patas": 2, "pico": 1, "alas": 2},
  "pingüino": {"patas": 2, "pico": 1, "alas": 2},
  "búho": {"patas": 2, "pico": 1, "alas": 2},
  "pavo real": {"patas": 2, "pico": 1, "alas": 2},
  "cisne": {"patas": 2, "pico": 1, "alas": 2},
  "cuervo": {"patas": 2, "pico": 1, "alas": 2},
  "halcón": {"patas": 2, "pico": 1, "alas": 2},
  "avestruz": {"patas": 2, "pico": 1, "alas": 2},
  "canario": {"patas": 2, "pico": 1, "alas": 2},
  "pez dorado": {"patas": 0, "pico": 1, "alas": 0},
  "tiburón": {"patas": 0, "pico": 1, "alas": 0},
  "salmón": {"patas": 0, "pico": 1, "alas": 0},
  "atún": {"patas": 0, "pico": 1, "alas": 0},
  "bacalao": {"patas": 0, "pico": 1, "alas": 0},
  "trucha": {"patas": 0, "pico": 1, "alas": 0},
  "pez payaso": {"patas": 0, "pico": 1, "alas": 0},
  "pez espada": {"patas": 0, "pico": 1, "alas": 0},
  "pez globo": {"patas": 0, "pico": 1, "alas": 0},
  "anguila": {"patas": 0, "pico": 1, "alas": 0},
  "lagarto": {"patas": 4, "pico": 1, "alas": 0},
  "serpiente": {"patas": 0, "pico": 1, "alas": 0},
  "tortuga": {"patas": 4, "pico": 1, "alas": 0},
  "cocodrilo": {"patas": 4, "pico": 1, "alas": 0},
  "iguana": {"patas": 4, "pico": 1, "alas": 0},
  "gecko": {"patas": 4, "pico": 1, "alas": 0},
  "dragón de komodo": {"patas": 4, "pico": 1, "alas": 0},
  "abeja": {"patas": 6, "pico": 1, "alas": 2},
  "mosca": {"patas": 6, "pico": 1, "alas": 2},
  "mariposa": {"patas": 6, "pico": 1, "alas": 2},
  "hormiga": {"patas": 6, "pico": 1, "alas": 0},
  "grillo": {"patas": 6, "pico": 1, "alas": 0},
  "saltamontes": {"patas": 6, "pico": 1, "alas": 2},
  "escarabajo": {"patas": 6, "pico": 1, "alas": 2},
  "cucaracha": {"patas": 6, "pico": 1, "alas": 2},
  "mantis": {"patas": 6, "pico": 1, "alas": 2},
  "libélula": {"patas": 6, "pico": 1, "alas": 2},
  "araña": {"patas": 8, "pico": 0, "alas": 0},
  "escorpión": {"patas": 8, "pico": 0, "alas": 0},
  "garrapata": {"patas": 8, "pico": 0, "alas": 0},
  "ácaro": {"patas": 8, "pico": 0, "alas": 0},
  "tarántula": {"patas": 8, "pico": 0, "alas": 0},
  "pulpo": {"patas": 8, "pico": 0, "alas": 0},
  "caracol": {"patas": 0, "pico": 0, "alas": 0},
  "calamar": {"patas": 0, "pico": 0, "alas": 0},
  "mejillón": {"patas": 0, "pico": 0, "alas": 0},
  "almeja": {"patas": 0, "pico": 0, "alas": 0},
  "ostra": {"patas": 0, "pico": 0, "alas": 0},
  "sepia": {"patas": 0, "pico": 0, "alas": 0}
}